version: "3"

services:
  backend:
    build:
      context: ./golang
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    # command: go run main.go
    volumes:
      - ./golang:/go/src
    environment:
      - TZ=Asia/Tokyo
  frontend:
    build: ./react
    stdin_open: true
    tty: true
    command: npm run dev
    volumes:
      - ./react:/app
    ports:
      - 5173:5173
volumes:
  mysql_data:
